// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }                  

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuScppMUcKEnhGHQmtMGwkUK2Q8e1pQ9s',
    appId: '1:748611206495:web:00e9a7cc2f57aff7198aea',
    messagingSenderId: '748611206495',
    projectId: 'app-despesas-flutter',
    authDomain: 'app-despesas-flutter.firebaseapp.com',
    storageBucket: 'app-despesas-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGxyqqJEBe925kgl8GbFMduO4lUU06YLk',
    appId: '1:748611206495:android:3ef4d08055b4171d198aea',
    messagingSenderId: '748611206495',
    projectId: 'app-despesas-flutter',
    storageBucket: 'app-despesas-flutter.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuScppMUcKEnhGHQmtMGwkUK2Q8e1pQ9s',
    appId: '1:748611206495:web:b03c2e560644add2198aea',
    messagingSenderId: '748611206495',
    projectId: 'app-despesas-flutter',
    authDomain: 'app-despesas-flutter.firebaseapp.com',
    storageBucket: 'app-despesas-flutter.firebasestorage.app',
  );

}